import type { NextPage } from "next";
import Head from "next/head";
import React, { useRef, useState, useMemo, useEffect } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { PerspectiveCamera, OrbitControls, Stage } from "@react-three/drei";
import styles from "../styles/Home.module.css";
import { boxesArray } from "./logo";
import { PerspectiveCamera as PerspectiveCameraType } from "three";

type Props = {
  meshprops: JSX.IntrinsicElements["mesh"];
  color: string;
};

const Home: NextPage = () => {
  const camera = React.useRef<PerspectiveCameraType>();

  const Box = (props: Props) => {
    // const mesh = useRef<THREE.Mesh>(null!);
    // Set up state for the hovered and active state
    const [hovered, setHover] = useState(false);
    const [active, setActive] = useState(false);
    // Subscribe this component to the render-loop, rotate the mesh every frame
    // useFrame((state, delta) => (mesh.current.rotation.x += 0.01));
    // Return the view, these are regular Threejs elements expressed in JSX

    return (
      <mesh
        {...props.meshprops}
        // ref={mesh}
        scale={active ? 1.5 : 1}
        // onClick={(event) => setActive(!active)}
        // onPointerOver={(event) => setHover(true)}
        // onPointerOut={(event) => setHover(false)}
      >
        <boxGeometry args={[1, 1, 1]} />
        <meshStandardMaterial color={props.color} />
      </mesh>
    );
  };

  const Boxes = () => {
    const meshRef = useRef<THREE.Mesh>(null!);
    useFrame((state, delta) => (meshRef.current.rotation.x += 0.01));

    return (
      <instancedMesh ref={meshRef}>
        {boxesArray.map((item, index) => (
          <Box
            key={index}
            meshprops={{ position: item.position }}
            color={item.color}
          />
        ))}
      </instancedMesh>
    );
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Canvas
          style={{
            width: 100 + "vw",
            height: 80 + "vh",
          }}
        >
          <PerspectiveCamera
            ref={camera}
            fov={75}
            position={[0, 0, 12]}
            makeDefault
          />
          <OrbitControls camera={camera.current} enableZoom={true} />
          <ambientLight />
          <pointLight position={[8, 8, 6]} />
          <Boxes />
        </Canvas>
      </main>
    </div>
  );
};

export default Home;
